# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='elect',
            fields=[
                ('EchoiceId', models.AutoField(primary_key=True, serialize=False, verbose_name='選択肢ID')),
                ('EchoiceName', models.CharField(max_length=200, verbose_name='選択肢名')),
                ('voteNum', models.IntegerField(default=0, verbose_name='獲得票数')),
            ],
        ),
        migrations.CreateModel(
            name='gradeFive',
            fields=[
                ('GchoiceId', models.AutoField(primary_key=True, serialize=False, verbose_name='選択肢ID')),
                ('GchoiceName', models.CharField(max_length=200, verbose_name='選択肢名')),
                ('one', models.IntegerField(default=0, verbose_name='評点1の票数')),
                ('two', models.IntegerField(default=0, verbose_name='評点2の票数')),
                ('three', models.IntegerField(default=0, verbose_name='評点3の票数')),
                ('four', models.IntegerField(default=0, verbose_name='評点4の票数')),
                ('five', models.IntegerField(default=0, verbose_name='評点5の票数')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False, verbose_name='部屋番号')),
                ('roomName', models.CharField(max_length=200, unique=True, verbose_name='部屋名')),
                ('password', models.CharField(max_length=32, verbose_name='合言葉')),
                ('roomInfo', models.TextField()),
                ('roomLimit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('voterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Room')),
            ],
        ),
        migrations.CreateModel(
            name='voteType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False, verbose_name='投票形式ID')),
                ('typeName', models.CharField(max_length=32, unique=True, verbose_name='投票形式名')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='creatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voteType'),
        ),
        migrations.AddField(
            model_name='gradefive',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Room'),
        ),
        migrations.AddField(
            model_name='elect',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Room'),
        ),
    ]
