# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(max_length=200, verbose_name='部屋名'),
        ),
    ]
