# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20170815_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetype',
            name='typeName',
            field=models.CharField(max_length=32, verbose_name='投票形式名'),
        ),
    ]
