# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_room_roombirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='typeId',
            field=models.ForeignKey(choices=[('1', '選出形式'), ('2', '評点形式')], on_delete=django.db.models.deletion.CASCADE, to='vote.voteType'),
        ),
    ]
