# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20170818_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voteType'),
        ),
    ]
