# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20170818_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomLimit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
