# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20170818_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomLimit',
            field=models.DateField(),
        ),
    ]
