# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20170818_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomBirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='部屋作成日'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomInfo',
            field=models.TextField(verbose_name='部屋説明文'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomLimit',
            field=models.DateField(verbose_name='投票期限'),
        ),
    ]
