# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20170920_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AddField(
            model_name='voter',
            name='voteId',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='投票番号'),
            preserve_default=False,
        ),
    ]
